
[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#657b83"
text = "#fdf6e3"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#fdf6e3"
foreground = "#657b83"

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Cousine NF"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true

[window.padding]
x = 4
y = 4

[general]
live_config_reload = true
