keymap:
  - name: firefox
    application: 
      only: firefox
    remap:
      C-backspace: c-f4               # Closetab
      C-SHIFT-backspace: c-shift-t    # Undo Close
      C-SHIFT-p: f6                   # C-SHIFT-l : toggle location bar
      M-minus: c-shift-tab            # M-[ : prev tab
      M-equal: c-tab                  # M-] : next tab
      M-SHIFT-minus: c-shift-pageup   # M-{ : move tab prev
      M-SHIFT-equal: c-shift-pagedown # M-} : move tab next
  - name: Pcmanfm
    application: 
      only: Pcmanfm
    remap:
      C-backspace: M-up # Go to parent directory
      C-h: pagedown     # C-d : Scroll up a page 
      C-f: pageup       # C-u : Scroll down a page
      C-u: home         # C-g : Scroll to Top
      C-SHIFT-u: end    # C-SHIFT-g : Scroll to End
      C-j: M-home       # C-h : Go to Home folder
      C-g: M-enter      # C-i : File Properties
      C-c: down         # C-j : down
      C-v: up           # C-k : up
      C-l: M-right      # C-n : forward
      C-r: M-left       # C-p : back
      C-o: f5           # C-r : refresh
      C-SHIFT-o: f2     # C-SHIFT-r : rename
      M-minus: f6       # M-[ : cycle pane
      M-equal: f6       # M-] : cycle pane

