virtual_modifiers:
  - compose # Aka 'Menu'
modmap:
  - name: ctrl_to_leftmeta
    remap:
      leftctrl: leftmeta
      rightctrl: leftmeta
  - name: capslock_tap_to_esc_hold_to_leftctrl
    remap:
      capslock:
        alone: esc
        held: leftctrl
        alone_timeout_millis: 100
  - name: tab_tap_to_tab_hold_to_alt
    remap:
      tab:
        alone: tab
        held: leftalt
        alone_timeout_millis: 100
  - name: leftshift_tap_to_delete_hold_to_leftshift
    remap:
      leftshift:
        alone: delete
        held: leftshift
        alone_timeout_millis: 100
keymap:
  - name: "Global"
    remap:
      # These are the menu-(numpad) keys:
      compose-u: key_7                # Compose-m : 7
      compose-i: key_8                # Compose-c : 8
      compose-o: key_9                # Compose-v : 9
      compose-p: key_kpasterisk       # Compose-l : asterisk
      compose-equal: key_kpslash      # Compose-] : forward-slash

      compose-h: key_e                # Compose-d : period
      compose-j: key_4                # Compose-h : 4
      compose-k: key_5                # Compose-t : 5
      compose-l: key_6                # Compose-n : 6
      compose-semicolon: key_kpplus   # Compose-s : plus
      # NOTE: conveniently, the minus is already mapped to the right of plus

      compose-n: key_0                # Compose-b : 0
      compose-m: key_1                # Compose-m : 1
      compose-comma: key_2            # Compose-w : 2
      compose-dot: key_3              # Compose-v : 3
      compose-slash: key_kpenter      # Compose-z : enter

      # These are the menu-(function) keys, which, we want for the moonlander:
      compose-grave: f1
      compose-key_1: f2
      compose-key_2: f3
      compose-key_3: f4
      compose-key_4: f5
      compose-key_5: f6
      compose-key_6: f7
      compose-key_7: f8
      compose-key_8: f9
      compose-key_9: f10
      compose-key_0: f11
      compose-minus: f12 # Compose-[ : f12

  - name: evince
    application:
      only: evince
    remap:
      C-u: c-home    # C-g - Begining of Document
      C-SHIFT-u: c-end   # C-S-g - End of Document
      C-f: pageup    # C-u - page up
      C-h: pagedown  # C-d - page down
  - name: firefox
    application: 
      only: firefox
    remap:
      C-backspace: c-f4               # Closetab
      C-SHIFT-backspace: c-shift-t    # Undo Close
      C-SHIFT-p: f6                   # C-SHIFT-l : toggle location bar
      C-l: M-right                    # C-n : forward
      C-r: M-left                     # C-p : backward
      M-minus: c-shift-tab            # M-[ : prev tab
      M-equal: c-tab                  # M-] : next tab
      M-SHIFT-minus: c-shift-pageup   # M-{ : move tab prev
      M-SHIFT-equal: c-shift-pagedown # M-} : move tab next
  - name: Pcmanfm
    application: 
      only: Pcmanfm
    remap:
      C-backspace: M-up # Go to parent directory
      C-h: pagedown     # C-d : Scroll up a page 
      C-f: pageup       # C-u : Scroll down a page
      C-u: home         # C-g : Scroll to Top
      C-SHIFT-u: end    # C-SHIFT-g : Scroll to End
      C-j: M-home       # C-h : Go to Home folder
      C-g: M-enter      # C-i : File Properties
      C-c: down         # C-j : down
      C-v: up           # C-k : up
      C-l: M-right      # C-n : forward
      C-r: M-left       # C-p : back
      C-o: f5           # C-r : refresh
      C-SHIFT-o: f2     # C-SHIFT-r : rename
      M-minus: f6       # M-[ : cycle pane
      M-equal: f6       # M-] : cycle pane
  - name: Telegram
    application: 
      only: /[Tt]elegram/
    remap:
      C-a: home                     # C-a: home (Insert mode)
      C-n: C-left                   # C-b: left (Insert mode)
      C-h: [SHIFT-right, backspace] # C-d: delete-next-char (Insert mode)
      C-j: backspace                # C-h: backspace (Insert mode)
      C-v: [SHIFT-end, backspace]   # C-k: delete to end of line (Insert mode)
      C-f: [SHIFT-home, backspace]  # C-u: delete to start of line (Insert mode)
      C-comma: C-backspace          # C-w: delete-prev-word (Insert mode)
      C-l: down                     # C-n: down
      C-r: up                       # C-p: up
      M-minus: c-shift-tab          # M-[ : prev chat
      M-equal: c-tab                # M-] : next chat
      M-h: pagedown                 # M-d: Page down
      M-f: pageup                   # M-u: Page up
  - name: vncviewer
    application: 
      only: /Vncviewer/
    remap:
      C-backspace: SHIFT-f8  # Show menu
      C-S-dot: SHIFT-insert  # C-SHIFT-v: putty paste
